#! /bin/sh

if [ -f $HOME/.autorun ]; then
	. $HOME/.autorun
fi
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

polybar main &

bspc config border_width         2
bspc config window_gap           0

bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color  "#001FBA"
bspc config normal_border_color   "#3C2E4F"
bspc config presel_feedback_color "#5FAFFF"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a HW2 state=floating

bspc config click_to_focus none
bspc config focus_follows_pointer true

bspc config ignore_ewmh_focus true
bspc rule -a code-oss desktop=1
bspc rule -a Code desktop=1
bspc rule -a VSCodium desktop=1
bspc rule -a discord desktop=8
bspc rule -a spotify desktop=9
bspc rule -a Spotify desktop=9
bspc rule -a jetbrains-rider desktop=1

