#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom -b &
nitrogen --restore &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

polybar &

#bspc config border_width         2
#bspc config window_gap          12
bspc config border_width         2
bspc config window_gap           0

#bspc config split_ratio          0.5
bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color  "#FF5555"
bspc config normal_border_color   "#303030"
bspc config presel_feedback_color "#FF5555"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config click_to_focus none
bspc config focus_follows_pointer true

bspc config ignore_ewmh_focus true
bspc rule -a code-oss desktop=1
bspc rule -a Code desktop=1
bspc rule -a VSCodium desktop=1
