#! /bin/sh

#if [ -f $HOME/autorun.sh ]; then
#    . $HOME/autorun.sh
#fi
pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor DisplayPort-2 -d 1 2 3 4 5 6 7
#bspc monitor HDMI-A-0 -d 8 9 0
bspc monitor DP-3 -d 1 2 3 4 5 6 7
bspc monitor HDMI-1 -d 8 9 0

#polybar main &
#polybar secondary &

bspc config border_width         2
bspc config window_gap           0

bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color  "#007373"
bspc config normal_border_color   "#303030"
bspc config presel_feedback_color "#007373"

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config click_to_focus none
bspc config focus_follows_pointer true

bspc config ignore_ewmh_focus true
#bspc rule -a code-oss desktop=1
#bspc rule -a Code desktop=1
#bspc rule -a VSCodium desktop=1
#bspc rule -a discord desktop=8
#bspc rule -a spotify desktop=9
#bspc rule -a Spotify desktop=9






# STARTUP
#/home/terrior/.config/autorun.sh

if [ -f $HOME/autorun.sh ]; then
    . $HOME/autorun.sh
fi


